<?php

use Illuminate\Database\Seeder;

class MallsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            ['id' => '1',
                'slug' => 'supermal-karawaci',
                'title' => 'Supermal Karawaci',
                'description' => 'Supermal Karawaci the first & one of the biggest shopping center in Indonesia',
                'city' => 'jakarta',
                'image' => 'malls/HIe7BV66eoCS8N88QWWyJpjkUpLMVo6ptj8kudt9.jpeg',
                'created_at' => '2017-12-06 08:07:46',
                'updated_at' => '2017-12-06 08:07:46',
            ],
            ['id' => '2',
                'slug' => 'lippo-mall-puri',
                'title' => 'Lippo Mall Puri',
                'description' => 'Located strategically at St. Moritz Superblock in CBD – West Jakarta, pampering you with Sogo, Parkson, Deluxe Cinema XXI and many more to offers!. It\'s a whole new shopping experience in town',
                'city' => 'Jakarta',
                'image' => 'malls/iNakCuQsIN6teWvCtAsMStvdCt6y7rWHtqPuCsez.jpeg',
                'created_at' => '2017-12-06 08:08:56',
                'updated_at' => '2017-12-06 08:08:56',
            ],
            ['id' => '3',
                'slug' => 'emporium-pluit-mall',
                'title' => 'Emporium Pluit Mall',
                'description' => 'Emporium Pluit Mall',
                'city' => 'jakarta',
                'image' => 'malls/9hYmI7rPCRs0yLbKroj24X6ts018L9l2zkJQUlbh.jpeg',
                'created_at' => '2017-12-06 08:11:09',
                'updated_at' => '2017-12-06 08:11:09',
            ],
            ['id' => '4',
                'slug' => 'aeon-mall-bsd-city',
                'title' => 'AEON MALL BSD CITY',
                'description' => 'AEON MALL BSD CITY',
                'city' => 'jakarta',
                'image' => 'malls/2VE9jCOMSMQnv69KN59KkEpFFLBTQd1zWbkaU4Vx.jpeg',
                'created_at' => '2017-12-06 08:12:10',
                'updated_at' => '2017-12-06 08:12:10',
            ],
            ['id' => '5',
                'slug' => 'baywalk-mall-pluit',
                'title' => 'Baywalk Mall - Pluit',
                'description' => 'Pluit Village',
                'city' => 'Jakarta',
                'image' => 'malls/B9Vh5XOHsVJeW4aWu7PLQ2aIvPaS6PKweAaqLxUp.jpeg',
                'created_at' => '2017-12-06 08:14:58',
                'updated_at' => '2017-12-06 08:14:58',
            ],
            ['id' => '6',
                'slug' => 'mal-taman-anggrek',
                'title' => 'Mal Taman Anggrek',
                'description' => 'Mal Taman Anggrek The best place in Jakarta for shopping, skating, eating, and entertainment. Follow us to get the most updated promo and offers at the mall.',
                'city' => 'Jakarta',
                'image' => 'malls/dFlhhDnlCmXzjvaBsoSF0jGob7cVc2aywaDGK8eL.jpeg',
                'created_at' => '2017-12-06 08:15:54',
                'updated_at' => '2017-12-06 08:15:54',
            ],
            ['id' => '7',
                'slug' => 'mal-artha-gading',
                'title' => 'Mal Artha Gading',
                'description' => 'Mal Artha Gading Penuh Canda, Penuh Warna',
                'city' => 'Jakarta',
                'image' => 'malls/UyHwoaHF8leX8BkOCAIrmK2cmIyTliTqrgS9grFH.jpeg',
                'created_at' => '2017-12-06 08:17:02',
                'updated_at' => '2017-12-06 08:17:02',
            ],
            ['id' => '8',
                'slug' => 'mall-of-indonesia',
                'title' => 'Mall of Indonesia',
                'description' => 'MOI The Fun Shopping Experience',
                'city' => 'Jakarta',
                'image' => 'malls/oJ2E5DVdms66hrRUzlxE23T5V99LnSuzqOBAUQV6.jpeg',
                'created_at' => '2017-12-06 08:18:34',
                'updated_at' => '2017-12-06 08:18:34',
            ],
            ['id' => '9',
                'slug' => 'mall-kuningan-city',
                'title' => 'Mall Kuningan City',
                'description' => 'The Essence of Urban Lifestyle Playground. Kuningan City is set to become the foremost destination for Urban Lifestyle Playground.',
                'city' => 'Jakarta',
                'image' => 'malls/WwmqWNqk1SWGbwFj2r1pLFqGpHvkfcIKIelm25B1.jpeg',
                'created_at' => '2017-12-06 08:21:57',
                'updated_at' => '2017-12-06 08:21:57',
            ],
            ['id' => '10',
                'slug' => 'pik-avenue',
                'title' => 'PIK Avenue',
                'description' => 'PIK Avenue',
                'city' => 'Jakarta',
                'image' => 'malls/q7U2ifFpKZgwTr5CgRiMsmjOSqOanyu8wObyfAZ1.jpeg',
                'created_at' => '2017-12-06 08:27:52',
                'updated_at' => '2017-12-06 08:27:52',
            ],
            ['id' => '11',
                'slug' => 'lippo-mall-kemang',
                'title' => 'Lippo Mall Kemang',
                'description' => 'Lippo Mall Kemang at Kemang Village 1500-252 Facebook: @lippomallkemang Twitter: @lippomallkemang www.lippomallkemang.com',
                'city' => 'Jakarta',
                'image' => 'malls/daueoQySo8lUeks3vkxa1J2goGZ7CetRACeUMecc.jpeg',
                'created_at' => '2017-12-06 08:29:25',
                'updated_at' => '2017-12-06 08:29:25',
            ],
            ['id' => '12',
                'slug' => 'central-park-mall',
                'title' => 'Central Park Mall',
                'description' => 'Central Park Mall Central Park Jakarta Official Instagram FB: Central Park Mall Jkt Twitter: @CentralParkMall www.centralparkjakarta.com',
                'city' => 'Jakarta',
                'image' => 'malls/ZOkND8pvIU9o8AFCnqbjD9APDurRG3z4tGY0yTC5.jpeg',
                'created_at' => '2017-12-06 08:30:04',
                'updated_at' => '2017-12-06 08:30:04',
            ],
            ['id' => '13',
                'slug' => 'gandaria-city',
                'title' => 'Gandaria City',
                'description' => 'A perfect combination of luxury, living, culinary experience and entertainment. South Jakarta\'s largest superblock of lifestyle. Gandaria City has it all.',
                'city' => 'Jakarta',
                'image' => 'malls/06LhUj3bSbc97ziWvEQpffGu2JxhDnjak64e2pyy.jpeg',
                'created_at' => '2017-12-06 08:31:23',
                'updated_at' => '2017-12-06 08:31:23',
            ],
            ['id' => '14',
                'slug' => 'kota-kasablanka',
                'title' => 'Kota Kasablanka',
                'description' => 'Kota Kasablanka Official Twitter. Facebook: Kota Kasablanka Instagram: @kotakasablanka Visit us at our website: http://kotakasablanka.co.id',
                'city' => 'Jakarta',
                'image' => 'malls/MLJWPrkLzC0Iu6q7TiwPDCeKB64eXu4ulBNwJ5AV.jpeg',
                'created_at' => '2017-12-06 08:33:53',
                'updated_at' => '2017-12-06 08:33:53',
            ],
            ['id' => '15',
                'slug' => 'mal-kelapa-gading',
                'title' => 'Mal Kelapa Gading',
                'description' => 'Mal Kelapa Gading Official account of Sentra Kelapa Gading',
                'city' => 'Jakarta',
                'image' => 'malls/40PPHMLJSbYAMCM5BiUKWDU4ZJkcL3wbfbtU29Qr.jpeg',
                'created_at' => '2017-12-06 08:35:31',
                'updated_at' => '2017-12-06 08:35:31',
            ],
            ['id' => '16',
                'slug' => 'lotte-shopping-avenue',
                'title' => 'LOTTE Shopping Avenue',
                'description' => 'LOTTE Shopping Avenue',
                'city' => 'Malang',
                'image' => 'malls/rgpLeF9YRNZDtMjSTRirQaSNIpDMCa7HzfMKBNKO.jpeg',
                'created_at' => '2017-12-06 08:36:40',
                'updated_at' => '2017-12-06 08:36:40',
            ],
            ['id' => '17',
                'slug' => 'metro-department-store',
                'title' => 'METRO Department Store',
                'description' => 'The official website of METRO Department Store Indonesia. Visit us for more information on our special offers and events',
                'city' => 'Jakarta',
                'image' => 'malls/59dgKbHOQCB5IacHKHFVde83PA2Nj0Tvnw2K3aTi.jpeg',
                'created_at' => '2017-12-06 08:38:37',
                'updated_at' => '2017-12-06 08:38:37',
            ],
            ['id' => '18',
                'slug' => 'grand-indonesia',
                'title' => 'Grand Indonesia',
                'description' => 'Grand Indonesia Official Account of Mall Grand Indonesia | Now open, FOODPRINT! Located at West Mall level 5 #GrandIndonesia www.grand-indonesia.com',
                'city' => 'Jakarta',
                'image' => 'malls/yQbnkeMMJLREn6VTr35BcgdBLWEoL9Lhk23Kq4Ue.jpeg',
                'created_at' => '2017-12-06 08:39:32',
                'updated_at' => '2017-12-06 08:39:32',
            ],
            ['id' => '19',
                'slug' => 'senayan-city',
                'title' => 'Senayan City',
                'description' => 'Senayan City',
                'city' => 'Jakarta',
                'image' => 'malls/ycmmePs3dWSY7vj0a5XIm6usYEyHrIy7yG8flURh.jpeg',
                'created_at' => '2017-12-06 08:40:10',
                'updated_at' => '2017-12-06 08:40:10',
            ],
            ['id' => '20',
                'slug' => 'plaza-indonesia',
                'title' => 'Plaza Indonesia',
                'description' => 'Plaza Indonesia',
                'city' => 'Jakarta',
                'image' => 'malls/blmaJyySHxebPBzkLTy6Ii0yiFY3Ctq0BpujHdbx.jpeg',
                'created_at' => '2017-12-06 08:41:45',
                'updated_at' => '2017-12-06 08:41:45',
            ],
            ['id' => '21',
                'slug' => 'pacific-place-jakarta',
                'title' => 'Pacific Place Jakarta',
                'description' => 'Pacific Place Jakarta Premium shopping & lifestyle center at the heart of Jakarta | Tag & share your picture to us with #PacificPlaceJakarta www.pacificplace.co.id',
                'city' => 'Jakarta',
                'image' => 'malls/v9IBIHTw5ll0XGMFXLLL8yHz0q8Ilv9RbabBfiic.jpeg',
                'created_at' => '2017-12-06 08:42:54',
                'updated_at' => '2017-12-06 08:42:54',
            ],
            ['id' => '22',
                'slug' => 'sogo-dept-store-indonesia',
                'title' => 'SOGO Dept Store Indonesia',
                'description' => 'SOGO Department Store Indonesia is one of the nation’s premier retailers with 15 stores all over Indonesia\'s big cities.
Part of http://www.mapemall.com/',
                'city' => 'Jakarta',
                'image' => 'malls/6Y6MlISfYqfW6PHlX040sd4By0qdvDG8nnwybLDy.jpeg',
                'created_at' => '2017-12-06 08:44:43',
                'updated_at' => '2017-12-06 08:44:43',
            ],
            ['id' => '23',
                'slug' => 'plaza-senayan',
                'title' => 'Plaza Senayan',
                'description' => 'Plaza Senayan Official Instagram of Plaza Senayan. Follow us to get the newest info on events, sales, and new shops at this elegant sophisticated shopping mall. plaza-senayan.com',
                'city' => 'Jakarta',
                'image' => 'malls/9WnEaIFvqrCYbELu5el7DcYyyhMVy6azZwS3ia1b.jpeg',
                'created_at' => '2017-12-06 08:45:36',
                'updated_at' => '2017-12-06 08:45:36',
            ],
        ];

        DB::table('malls')->truncate();
        DB::table('malls')->insert($data);
    }
}
